[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phoenix"
version = "1.0"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["phoenix"]
